// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/leaderboard": {
            "get": {
                "description": "Sends back the leaderboard in descending order of level, and for users on the same level, in the ascending order of last successful submission time.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Kryptos",
                    "auth_required"
                ],
                "summary": "return leaderboard.",
                "responses": {
                    "200": {
                        "description": "Returns the leaderboard",
                        "schema": {
                            "$ref": "#/definitions/handlers.swag_user"
                        }
                    },
                    "500": {
                        "description": "Could not serialize json",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/ping": {
            "get": {
                "description": "Sends \"Test\" back. Use this to check if the server is up.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Kryptos"
                ],
                "summary": "Server health check.",
                "responses": {
                    "200": {
                        "description": "Server is up",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.swag_user": {
            "type": "object",
            "properties": {
                "curr_level": {
                    "type": "integer",
                    "example": 18
                },
                "name": {
                    "type": "string",
                    "example": "Aswin G"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "Excel Play Kryptos API",
	Description: "This is the swagger doc for the API for Excel Play Kryptos.",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
